[package]
authors     = ["magic-akari <akari.ccino@gmail.com>"]
description = "[SWC plugin] workaround for jest"
edition     = "2021"
homepage    = "https://github.com/magic-akari/jest_workaround"
keywords    = ["swc-plugin", "jest"]
license     = "MIT"
name        = "jest_workaround"
readme      = "README.md"
repository  = "https://github.com/magic-akari/jest_workaround"
version     = "0.1.13"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
indexmap = "1.9.1"
serde = "1.0.145"
swc_core = { version = "0.38.7", features = [
    "ecma_ast",
    "ecma_visit",
    "swc_plugin",
    "ecma_utils",
    "swc_atoms",
    "plugin_transform",
    "__parser"
] }


[dev-dependencies]
swc_core = { version = "0.38.7", features = ["testing_transform"] }
testing  = "0.31.8"

[profile.release]
strip = "debuginfo"
